version: "3.9"

services:
  stac-api:
    container_name: stac-fastapi-os
    image: stac-dms/stac-fastapi-os
    restart: always
    build:
      context: ./api
      target: development
    ports:
      - 8000:8000
    expose:
      - 8000
    environment:
      - STAC_FASTAPI_TITLE=stac-fastapi-opensearch
      - STAC_FASTAPI_DESCRIPTION=A STAC FastAPI with an Opensearch backend
      - STAC_FASTAPI_VERSION=3.0.0a2
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - RELOAD=true
      - ENVIRONMENT=local
      - WEB_CONCURRENCY=10
      - ES_HOST=opensearch
      - ES_PORT=9202
      - ES_USE_SSL=false
      - ES_VERIFY_CERTS=false
      - BACKEND=opensearch
    volumes:
      - ./api/dmsapi:/app/dmsapi
      - ./api/scripts:/app/scripts
      # - ./osdata:/usr/share/opensearch/data
    depends_on:
      - opensearch
    command: bash -c "./scripts/wait-for-it.sh os-container:9202 && python -m dmsapi.app"

  opensearch:
    container_name: os-container
    image: opensearchproject/opensearch:2.15.0
    hostname: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./api/opensearch/config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - ./api/opensearch/snapshots:/usr/share/opensearch/snapshots
    ports:
      - "9202:9202"
      - 9600:9600

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.15.0 # Make sure the version of opensearch-dashboards matches the version of opensearch installed on other nodes
    container_name: opensearch-dashboards
    ports:
      - 5601:5601 # Map host port 5601 to container port 5601
    expose:
      - 5601 # Expose port 5601 for web access to OpenSearch Dashboards
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9202"]' # Define the OpenSearch nodes that OpenSearch Dashboards will query
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: true # disables security dashboards plugin in OpenSearch Dashboards

  stac-dms:
    build:
      context: ./frontend
      target: run-dev
    ports:
      - 24678:24678
      - 3000:3000
    container_name: stac-dms-frontend
    image: stac-dms/frontend
    volumes:
      - ./frontend:/src

  stac-proxy:
    container_name: stac-proxy
    image: stac-dms/proxy
    build:
      context: ./proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/Caddyfile:/etc/caddy/Caddyfile
      - ./proxy/data/data:/data
      - ./proxy/data/config:/config
    depends_on:
      - stac-api
      - stac-dms
    environment:
      - DOMAIN=localhost
      - PROXY_BACKEND_HOST=stac-fastapi-os
      - PROXY_BACKEND_PORT=8000
      - PROXY_FRONTEND_HOST=stac-dms
      - PROXY_FRONTEND_PORT=3000
