"""null constraints on keywords

Revision ID: c147404fda3c
Revises: d47d891117c8
Create Date: 2024-08-26 08:15:37.067158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c147404fda3c'
down_revision: Union[str, None] = 'd47d891117c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('keyword', 'nl_keyword',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('keyword', 'en_keyword',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('keyword', 'group_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('keyword_group_id_fkey', 'keyword', type_='foreignkey')
    op.create_foreign_key(None, 'keyword', 'keyword_group', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'keyword', type_='foreignkey')
    op.create_foreign_key('keyword_group_id_fkey', 'keyword', 'keyword_group', ['group_id'], ['id'])
    op.alter_column('keyword', 'group_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('keyword', 'en_keyword',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('keyword', 'nl_keyword',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
