ARG NODE_VERSION=22.21.1

FROM node:${NODE_VERSION} AS base

ARG PORT=3000
WORKDIR /src

FROM base AS base-dev

ENV NODE_ENV=development

FROM base AS base-prod

ENV NODE_ENV=production

# Build 
FROM base-dev AS build-dev

COPY --link package.json package-lock.json ./
RUN npm install

# Build
FROM base-prod AS build-prod

COPY --link package.json package-lock.json ./
RUN npm install --production=false

COPY --link . .

RUN npm run build
RUN npm prune

# Run 
FROM base-dev AS run-dev

COPY --from=build-dev /src/node_modules /src/node_modules
COPY --from=build-dev /src/package.json /src/package.json

# Copy source code to enable pre-compilation
COPY --from=build-dev /src/.nuxt /src/.nuxt
COPY --link . .

# Pre-compile Nuxt to avoid cold start
RUN npm run build || true

CMD [ "npm", "run", "dev" ]

# Run
FROM base-prod AS run-prod

ENV PORT=$PORT

COPY --from=build-prod /src/.output /src/.output
COPY --from=build-prod /src/content /src/content
# Optional, only needed if you rely on unbundled dependencies
# COPY --from=build-prod /src/node_modules /src/node_modules

CMD [ "node", ".output/server/index.mjs" ]
