// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 13-3-2025, 09:06:24
const configMerger = require("D:/repos/stac-dms-5/frontend/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["D:/repos/stac-dms-5/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/repos/stac-dms-5/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/repos/stac-dms-5/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/repos/stac-dms-5/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/repos/stac-dms-5/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/repos/stac-dms-5/frontend/plugins/**/*.{js,ts,mjs}","D:/repos/stac-dms-5/frontend/composables/**/*.{js,ts,mjs}","D:/repos/stac-dms-5/frontend/utils/**/*.{js,ts,mjs}","D:/repos/stac-dms-5/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/repos/stac-dms-5/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/repos/stac-dms-5/frontend/app.config.{js,ts,mjs}"] }));

module.exports = config
