[workspace]
authors = ["JoerivanEngelen <joerivanengelen@hotmail.com>"]
channels = ["conda-forge"]
name = "fdf-docs"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
install_tinytex = "quarto install tinytex"
render_pdf = "quarto render user_manual.qmd --to pdf --output user_manual.pdf"
render_html = "quarto render user_manual.qmd --to html --output user_manual.html"

[dependencies]
quarto = ">=1.7.32,<2"
