"""add facility type to keyword group

Revision ID: 83d66cb945c2
Revises: ced79c82eaee
Create Date: 2025-07-01 09:55:05.147533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '83d66cb945c2'
down_revision: Union[str, None] = 'ced79c82eaee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1: Add nullable column
    op.add_column('keyword_group', sa.Column('facility_type', sqlmodel.AutoString(), nullable=True))
    
    # Step 2: Update existing rows with a default value
    op.execute("UPDATE keyword_group SET facility_type = 'numericalModel' WHERE facility_type IS NULL")
    
    # Step 3: Make column NOT NULL
    op.alter_column('keyword_group', 'facility_type', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keyword_group', 'facility_type')
    # ### end Alembic commands ###
