"""set global permissions to nullable

Revision ID: b138775c00dd
Revises: 48a497f220a8
Create Date: 2025-04-02 12:50:38.211637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'b138775c00dd'
down_revision: Union[str, None] = '48a497f220a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grouprole', sa.Column('object', sqlmodel.AutoString(), nullable=True))
    op.drop_column('grouprole', 'object_id')
    op.sync_enum_values(
        enum_schema='public',
        enum_name='role_enum',
        new_values=['DATA_PRODUCER', 'COLLECTION_DATA_STEWARD', 'ADMIN', 'KEYWORD_EDITOR', 'APPLICATION_DATA_STEWARD'],
        affected_columns=[TableReference(table_schema='public', table_name='grouprole', column_name='role')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='role_enum',
        new_values=['DATA_STEWARD', 'DATA_PRODUCER', 'ADMIN', 'KEYWORD_EDITOR'],
        affected_columns=[TableReference(table_schema='public', table_name='grouprole', column_name='role')],
        enum_values_to_rename=[],
    )
    op.add_column('grouprole', sa.Column('object_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('grouprole', 'object')
    # ### end Alembic commands ###
